#!/usr/bin/env python3
"""Unified loader for every inverse-folding epitope design in this project.

Two corpora, generated by different pipelines, are harmonised into one tidy table:

  panel     20 pMHC-TCR crystals, the set the paper is written on. Designs live as
            raw FASTA under outputs/panel/{pdb}/{arm}/{model}/seqs/.
  skempi    28 SKEMPI-derived pMHC-TCR complexes, disjoint from the panel.
  focus6am  6AM5 / 6AMU, the DMF5 cross-reactive pair.
            Both of the latter arrive as gzipped tidy CSVs under designs/{dataset}/t01/.

Schema (one row per design):

  dataset   panel | skempi | focus6am
  complex   crystal id (panel: '2P5W'; skempi: '1BD2_ABC_DE')
  pdb       four-letter code, comparable across corpora
  arm       full | mhconly       (the new corpus calls mhconly 'notcr'; renamed here)
  model     vanilla | noMHC | ESM-IF1 | LigandMPNN   (repo-internal keys, see MODEL_LABEL)
  seq       designed epitope
  native    crystallographic epitope
  recovery  per-position identity to native

Naming: the new pipeline emits proteinmpnn / proteinmpnn_nomhc / esmif / ligandmpnn and
full / notcr. Those are mapped onto the repo's existing keys so that notebooks written
against the panel keep working unchanged.

Usage:
    from design_corpus import load_corpus, MODELS, MODEL_LABEL
    df = load_corpus()                      # everything, cached
    df = load_corpus(datasets=["skempi"])   # one corpus

Building the cache from scratch walks ~1.6M FASTA records and takes a few minutes;
after that it is a parquet read. Force a rebuild with load_corpus(rebuild=True).
"""
from __future__ import annotations

import gzip
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / "outputs/design_corpus.parquet"

MODELS = ["vanilla", "noMHC", "ESM-IF1", "LigandMPNN"]
MODEL_LABEL = {
    "vanilla": "ProteinMPNN",
    "noMHC": "ProteinMPNN (no MHC)",
    "ESM-IF1": "ESM-IF1",
    "LigandMPNN": "LigandMPNN",
}
MODEL_COLOR = {
    "vanilla": "#0072B2",
    "noMHC": "#E69F00",
    "ESM-IF1": "#009E73",
    "LigandMPNN": "#CC79A7",
}
ARMS = ["full", "mhconly"]
ARM_LABEL = {"full": "pMHC+TCR", "mhconly": "pMHC only"}

# new-pipeline vocabulary -> repo-internal keys
MODEL_FROM_NEW = {
    "proteinmpnn": "vanilla",
    "proteinmpnn_nomhc": "noMHC",
    "esmif": "ESM-IF1",
    "ligandmpnn": "LigandMPNN",
}
ARM_FROM_NEW = {"full": "full", "notcr": "mhconly"}

PANEL_STRUCTS = ["2P5W", "1QSF", "1QRN", "2BNR", "2GJ6", "2F53", "2F54", "3QDG", "3QEQ", "3QFJ",
                 "3GSN", "1OGA", "3UTS", "5C0A", "5C0B", "5HHO", "5EU6", "2VLR", "4MJI", "5NME"]
NEW_DATASETS = ["skempi", "focus6am"]


# --------------------------------------------------------------------------- panel (FASTA)

def _header_fields(header: str) -> dict[str, float]:
    """Parse the 'key=value, key=value' tail of a ProteinMPNN/LigandMPNN/ESM-IF FASTA header."""
    out = {}
    for tok in header.lstrip(">").split(","):
        if "=" not in tok:
            continue
        k, _, v = tok.partition("=")
        try:
            out[k.strip()] = float(v.strip())
        except ValueError:
            pass
    return out


def _fasta_records(path: Path, ligandmpnn: bool = False,
                   skip_native_echo: bool = False) -> list[tuple[str, dict]]:
    """(peptide, header-fields) for every record in a design FASTA.

    LigandMPNN writes the whole complex colon-joined, so the epitope is field 2.

    ProteinMPNN and LigandMPNN both echo the *input* sequence back as the first record
    (ProteinMPNN tags it with global_score and no per-sample score; LigandMPNN writes the
    native complex). That echo is not a design -- it is the native peptide -- so counting
    it inflates every cell by one perfect-recovery sequence. `skip_native_echo` drops it.
    ESM-IF writes designs only and needs no skipping.
    """
    if not path.exists():
        return []
    lines = path.read_text().splitlines()
    out = []
    for i in range(0, len(lines) - 1, 2):
        if not lines[i].startswith(">"):
            continue
        s = lines[i + 1].strip()
        out.append((s.split(":")[2] if ligandmpnn else s, _header_fields(lines[i])))
    if skip_native_echo and out:
        out = out[1:]
    return out


def load_panel(structs: list[str] | None = None) -> pd.DataFrame:
    """The paper's twenty-structure panel, read from its FASTA outputs."""
    structs = structs or PANEL_STRUCTS
    meta = pd.read_csv(ROOT / "inputs/pmhc_tcr_dataset/dataset.csv")
    natives = dict(zip(meta["pdb"], meta["peptide"]))

    rows = []
    for pdb in structs:
        native = natives[pdb]
        for arm in ARMS:
            base = ROOT / f"outputs/panel/{pdb}/{arm}"
            sources = [
                ("vanilla", base / f"mpnn/seqs/vanilla_{pdb}.fa", False, True),
                ("noMHC", base / f"mpnn/seqs/nomhc_{pdb}.fa", False, True),
                ("ESM-IF1", base / f"esmif/seqs/{pdb}.fa", False, False),
                ("LigandMPNN", base / f"ligandmpnn/seqs/{pdb}.fa", True, True),
            ]
            for model, path, is_lmpnn, echo in sources:
                # LigandMPNN reports overall_confidence (higher = better); the MPNN pair and
                # ESM-IF report an NLL-style score (lower = better). Kept raw here; load_corpus
                # derives a sign-consistent `confidence`.
                skey = "overall_confidence" if is_lmpnn else "score"
                gkey = "ligand_confidence" if is_lmpnn else "global_score"
                for seq, h in _fasta_records(path, is_lmpnn, skip_native_echo=echo):
                    rows.append((pdb, arm, model, seq, native, h.get(skey), h.get(gkey)))

    df = pd.DataFrame(rows, columns=["complex", "arm", "model", "seq", "native",
                                     "score", "global_score"])
    df["dataset"] = "panel"
    df["pdb"] = df["complex"]
    return df


# --------------------------------------------------------------------------- new (tidy CSV)

def load_new_dataset(dataset: str, temp: str = "t01") -> pd.DataFrame:
    """One of the gzipped tidy-CSV corpora under designs/{dataset}/{temp}/."""
    d = ROOT / "designs" / dataset / temp
    if not d.exists():
        raise FileNotFoundError(f"no design directory at {d}")
    parts = []
    for f in sorted(d.glob("*.csv.gz")):
        sub = pd.read_csv(f, usecols=lambda c: c in
                          {"complex", "arm", "model", "seq", "native", "score", "global_score"})
        parts.append(sub)
    df = pd.concat(parts, ignore_index=True)
    df["model"] = df["model"].map(MODEL_FROM_NEW)
    df["arm"] = df["arm"].map(ARM_FROM_NEW)
    if df["model"].isna().any() or df["arm"].isna().any():
        raise ValueError(f"{dataset}: unmapped model/arm vocabulary")
    df["dataset"] = dataset
    df["pdb"] = df["complex"].str.split("_").str[0]
    return df


# --------------------------------------------------------------------------- combined

def _recovery(seq: str, native: str) -> float:
    if len(seq) != len(native):
        return np.nan
    return sum(a == b for a, b in zip(seq, native)) / len(native)


def build_corpus() -> pd.DataFrame:
    frames = [load_panel()] + [load_new_dataset(d) for d in NEW_DATASETS]
    df = pd.concat(frames, ignore_index=True)
    # recompute recovery uniformly rather than trusting two pipelines to agree
    df["recovery"] = [_recovery(s, n) for s, n in zip(df["seq"], df["native"])]
    df["pep_len"] = df["native"].str.len()
    # sign-consistent confidence: higher always means the model is surer of its own design.
    # LigandMPNN's score field is overall_confidence in both pipelines (see mpnn_collect.py),
    # the ProteinMPNN pair reports a negative log-likelihood.
    df["confidence"] = np.where(df["model"] == "LigandMPNN", df["score"], -df["score"])
    for c in ["dataset", "complex", "pdb", "arm", "model"]:
        df[c] = df[c].astype("category")
    return df


def load_corpus(datasets: list[str] | None = None, rebuild: bool = False) -> pd.DataFrame:
    if rebuild or not CACHE.exists():
        df = build_corpus()
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        df.to_parquet(CACHE, index=False)
    else:
        df = pd.read_parquet(CACHE)
    if datasets is not None:
        df = df[df["dataset"].isin(datasets)].copy()
    return df


# --------------------------------------------------------------------------- per-position

def per_position_recovery(df: pd.DataFrame) -> pd.DataFrame:
    """Long table of per-position recovery, one row per (dataset, complex, arm, model, position).

    Positions are 1-indexed. `pos_label` names them the way the paper does: P1, P2, ...
    for the N-terminal side and POmega for the C-terminal anchor.
    """
    out = []
    keys = ["dataset", "complex", "pdb", "arm", "model"]
    for key, g in df.groupby(keys, observed=True):
        native = g["native"].iloc[0]
        L = len(native)
        seqs = [s for s in g["seq"] if len(s) == L]
        if not seqs:
            continue
        arr = np.frombuffer("".join(seqs).encode(), dtype="S1").reshape(len(seqs), L)
        nat = np.frombuffer(native.encode(), dtype="S1")
        rec = (arr == nat).mean(axis=0)
        for i in range(L):
            out.append((*key, i + 1, L, native[i], rec[i], len(seqs)))
    res = pd.DataFrame(out, columns=keys + ["pos", "pep_len", "native_aa", "recovery", "n"])
    res["pos_label"] = np.where(res["pos"] == res["pep_len"], "POmega", "P" + res["pos"].astype(str))
    res["region"] = np.select(
        [res["pos"] == 1, res["pos"] == 2, res["pos"] == res["pep_len"]],
        ["P1", "P2", "POmega"], default="interior")
    return res


if __name__ == "__main__":
    df = load_corpus(rebuild=True)
    print(f"{len(df):,} designs")
    print(df.groupby(["dataset", "model", "arm"], observed=True)
            .agg(complexes=("complex", "nunique"), n=("seq", "size"),
                 unique=("seq", "nunique"), recovery=("recovery", "mean")).to_string())
